# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon Mar 26 14:40:06 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CANalyzatorMainWindow(object):
    def setupUi(self, CANalyzatorMainWindow):
        CANalyzatorMainWindow.setObjectName("CANalyzatorMainWindow")
        CANalyzatorMainWindow.resize(1178, 715)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CANalyzatorMainWindow.sizePolicy().hasHeightForWidth())
        CANalyzatorMainWindow.setSizePolicy(sizePolicy)
        CANalyzatorMainWindow.setMinimumSize(QtCore.QSize(1178, 715))
        CANalyzatorMainWindow.setMaximumSize(QtCore.QSize(1178, 715))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CANalyzatorMainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(CANalyzatorMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1178, 693))
        self.centralwidget.setMaximumSize(QtCore.QSize(1178, 693))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgetMain = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setGeometry(QtCore.QRect(0, 0, 1171, 351))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetMain.sizePolicy().hasHeightForWidth())
        self.tabWidgetMain.setSizePolicy(sizePolicy)
        self.tabWidgetMain.setMinimumSize(QtCore.QSize(1171, 351))
        self.tabWidgetMain.setMaximumSize(QtCore.QSize(1512, 351))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.tabWidgetMain.setFont(font)
        self.tabWidgetMain.setStyleSheet("color : black")
        self.tabWidgetMain.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidgetMain.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tabMain = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setObjectName("tabMain")
        self.groupBoxIfaceConfig = QtGui.QGroupBox(self.tabMain)
        self.groupBoxIfaceConfig.setGeometry(QtCore.QRect(30, 80, 391, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupBoxIfaceConfig.setFont(font)
        self.groupBoxIfaceConfig.setObjectName("groupBoxIfaceConfig")
        self.layoutWidget = QtGui.QWidget(self.groupBoxIfaceConfig)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 357, 163))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayoutMainIfaceConfig = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayoutMainIfaceConfig.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutMainIfaceConfig.setObjectName("gridLayoutMainIfaceConfig")
        self.buttonVCANRemove = QtGui.QPushButton(self.layoutWidget)
        self.buttonVCANRemove.setObjectName("buttonVCANRemove")
        self.gridLayoutMainIfaceConfig.addWidget(self.buttonVCANRemove, 5, 2, 1, 2)
        self.checkBoxMainUseVCAN = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxMainUseVCAN.setMinimumSize(QtCore.QSize(200, 0))
        self.checkBoxMainUseVCAN.setChecked(True)
        self.checkBoxMainUseVCAN.setObjectName("checkBoxMainUseVCAN")
        self.gridLayoutMainIfaceConfig.addWidget(self.checkBoxMainUseVCAN, 3, 0, 1, 1)
        self.buttonReadInterfaces = QtGui.QPushButton(self.layoutWidget)
        self.buttonReadInterfaces.setObjectName("buttonReadInterfaces")
        self.gridLayoutMainIfaceConfig.addWidget(self.buttonReadInterfaces, 5, 0, 1, 1)
        self.labelRate = QtGui.QLabel(self.layoutWidget)
        self.labelRate.setObjectName("labelRate")
        self.gridLayoutMainIfaceConfig.addWidget(self.labelRate, 1, 0, 1, 1)
        self.buttonApplyInterface = QtGui.QPushButton(self.layoutWidget)
        self.buttonApplyInterface.setObjectName("buttonApplyInterface")
        self.gridLayoutMainIfaceConfig.addWidget(self.buttonApplyInterface, 4, 0, 1, 1)
        self.labelMainGlobalIface = QtGui.QLabel(self.layoutWidget)
        self.labelMainGlobalIface.setMinimumSize(QtCore.QSize(190, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.labelMainGlobalIface.setFont(font)
        self.labelMainGlobalIface.setObjectName("labelMainGlobalIface")
        self.gridLayoutMainIfaceConfig.addWidget(self.labelMainGlobalIface, 0, 0, 1, 1)
        self.labelVCANIndex = QtGui.QLabel(self.layoutWidget)
        self.labelVCANIndex.setObjectName("labelVCANIndex")
        self.gridLayoutMainIfaceConfig.addWidget(self.labelVCANIndex, 3, 2, 1, 1)
        self.buttonVCANAdd = QtGui.QPushButton(self.layoutWidget)
        self.buttonVCANAdd.setObjectName("buttonVCANAdd")
        self.gridLayoutMainIfaceConfig.addWidget(self.buttonVCANAdd, 4, 2, 1, 2)
        self.spinBoxVCANIndex = QtGui.QSpinBox(self.layoutWidget)
        self.spinBoxVCANIndex.setMaximum(9)
        self.spinBoxVCANIndex.setObjectName("spinBoxVCANIndex")
        self.gridLayoutMainIfaceConfig.addWidget(self.spinBoxVCANIndex, 3, 3, 1, 1)
        self.comboBoxInterface = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxInterface.setObjectName("comboBoxInterface")
        self.gridLayoutMainIfaceConfig.addWidget(self.comboBoxInterface, 0, 2, 1, 2)
        self.spinBoxBitrate = QtGui.QSpinBox(self.layoutWidget)
        self.spinBoxBitrate.setMinimum(1)
        self.spinBoxBitrate.setMaximum(1000000)
        self.spinBoxBitrate.setSingleStep(10000)
        self.spinBoxBitrate.setProperty("value", 500000)
        self.spinBoxBitrate.setObjectName("spinBoxBitrate")
        self.gridLayoutMainIfaceConfig.addWidget(self.spinBoxBitrate, 1, 2, 1, 2)
        self.groupBoxMainCurrentProject = QtGui.QGroupBox(self.tabMain)
        self.groupBoxMainCurrentProject.setGeometry(QtCore.QRect(800, 80, 331, 101))
        self.groupBoxMainCurrentProject.setObjectName("groupBoxMainCurrentProject")
        self.layoutWidget1 = QtGui.QWidget(self.groupBoxMainCurrentProject)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 291, 63))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayoutMainCurrentProject = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayoutMainCurrentProject.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutMainCurrentProject.setObjectName("gridLayoutMainCurrentProject")
        self.buttonSetProject = QtGui.QPushButton(self.layoutWidget1)
        self.buttonSetProject.setObjectName("buttonSetProject")
        self.gridLayoutMainCurrentProject.addWidget(self.buttonSetProject, 1, 0, 1, 2)
        self.comboBoxProjectSet = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxProjectSet.setObjectName("comboBoxProjectSet")
        self.gridLayoutMainCurrentProject.addWidget(self.comboBoxProjectSet, 0, 1, 1, 1)
        self.labelActiveProject = QtGui.QLabel(self.layoutWidget1)
        self.labelActiveProject.setObjectName("labelActiveProject")
        self.gridLayoutMainCurrentProject.addWidget(self.labelActiveProject, 0, 0, 1, 1)
        self.groupBoxMainLogging = QtGui.QGroupBox(self.tabMain)
        self.groupBoxMainLogging.setGeometry(QtCore.QRect(800, 220, 331, 71))
        self.groupBoxMainLogging.setObjectName("groupBoxMainLogging")
        self.layoutWidget2 = QtGui.QWidget(self.groupBoxMainLogging)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 30, 291, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayoutMainLogging = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayoutMainLogging.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutMainLogging.setObjectName("horizontalLayoutMainLogging")
        self.labelLoglevel = QtGui.QLabel(self.layoutWidget2)
        self.labelLoglevel.setObjectName("labelLoglevel")
        self.horizontalLayoutMainLogging.addWidget(self.labelLoglevel)
        self.comboBoxLoglevel = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxLoglevel.setObjectName("comboBoxLoglevel")
        self.comboBoxLoglevel.addItem("")
        self.comboBoxLoglevel.addItem("")
        self.comboBoxLoglevel.addItem("")
        self.comboBoxLoglevel.addItem("")
        self.comboBoxLoglevel.addItem("")
        self.horizontalLayoutMainLogging.addWidget(self.comboBoxLoglevel)
        self.labelMainCANalyzat0r = QtGui.QLabel(self.tabMain)
        self.labelMainCANalyzat0r.setGeometry(QtCore.QRect(410, 30, 391, 61))
        font = QtGui.QFont()
        font.setFamily("OCRA")
        font.setPointSize(36)
        font.setWeight(75)
        font.setBold(True)
        self.labelMainCANalyzat0r.setFont(font)
        self.labelMainCANalyzat0r.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelMainCANalyzat0r.setObjectName("labelMainCANalyzat0r")
        self.labelMainLogo = QtGui.QLabel(self.tabMain)
        self.labelMainLogo.setGeometry(QtCore.QRect(460, 50, 311, 271))
        self.labelMainLogo.setText("")
        self.labelMainLogo.setPixmap(QtGui.QPixmap("icon/icon.png"))
        self.labelMainLogo.setScaledContents(True)
        self.labelMainLogo.setObjectName("labelMainLogo")
        self.tabWidgetMain.addTab(self.tabMain, "")
        self.tabSniffer = QtGui.QWidget()
        self.tabSniffer.setObjectName("tabSniffer")
        self.tabWidgetSnifferTabs = QtGui.QTabWidget(self.tabSniffer)
        self.tabWidgetSnifferTabs.setGeometry(QtCore.QRect(0, 0, 1181, 331))
        self.tabWidgetSnifferTabs.setMovable(True)
        self.tabWidgetSnifferTabs.setObjectName("tabWidgetSnifferTabs")
        self.tabSnifferPlaceholder = QtGui.QWidget()
        self.tabSnifferPlaceholder.setObjectName("tabSnifferPlaceholder")
        self.tabWidgetSnifferTabs.addTab(self.tabSnifferPlaceholder, "")
        self.tabWidgetMain.addTab(self.tabSniffer, "")
        self.tabSender = QtGui.QWidget()
        self.tabSender.setObjectName("tabSender")
        self.tabWidgetSenderTabs = QtGui.QTabWidget(self.tabSender)
        self.tabWidgetSenderTabs.setGeometry(QtCore.QRect(0, 0, 1181, 331))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tabWidgetSenderTabs.setFont(font)
        self.tabWidgetSenderTabs.setMovable(True)
        self.tabWidgetSenderTabs.setObjectName("tabWidgetSenderTabs")
        self.tabSinglePacket = QtGui.QWidget()
        self.tabSinglePacket.setObjectName("tabSinglePacket")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabSinglePacket)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 1171, 281))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayoutSinglePacketOverall = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutSinglePacketOverall.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutSinglePacketOverall.setObjectName("gridLayoutSinglePacketOverall")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutSinglePacketOverall.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutSinglePacketOverall.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutSinglePacketOverall.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayoutSinglePacket = QtGui.QGridLayout()
        self.gridLayoutSinglePacket.setObjectName("gridLayoutSinglePacket")
        self.labelSenderSingleInterfaceDescr = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSenderSingleInterfaceDescr.setObjectName("labelSenderSingleInterfaceDescr")
        self.gridLayoutSinglePacket.addWidget(self.labelSenderSingleInterfaceDescr, 2, 0, 1, 2)
        self.lineEditSinglePacketID = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditSinglePacketID.setObjectName("lineEditSinglePacketID")
        self.gridLayoutSinglePacket.addWidget(self.lineEditSinglePacketID, 5, 2, 1, 2)
        self.labelSinglePacketID = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSinglePacketID.setObjectName("labelSinglePacketID")
        self.gridLayoutSinglePacket.addWidget(self.labelSinglePacketID, 5, 0, 1, 2)
        self.labelSinglePackeData = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSinglePackeData.setObjectName("labelSinglePackeData")
        self.gridLayoutSinglePacket.addWidget(self.labelSinglePackeData, 6, 0, 1, 2)
        self.lineEditSinglePacketData = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEditSinglePacketData.setObjectName("lineEditSinglePacketData")
        self.gridLayoutSinglePacket.addWidget(self.lineEditSinglePacketData, 6, 2, 1, 2)
        self.buttonSingleSend = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.buttonSingleSend.setObjectName("buttonSingleSend")
        self.gridLayoutSinglePacket.addWidget(self.buttonSingleSend, 7, 0, 1, 4)
        self.labelSenderSingleInterfaceValue = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelSenderSingleInterfaceValue.setObjectName("labelSenderSingleInterfaceValue")
        self.gridLayoutSinglePacket.addWidget(self.labelSenderSingleInterfaceValue, 2, 2, 1, 2)
        self.buttonSenderSingleInterfaceSettings = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.buttonSenderSingleInterfaceSettings.setObjectName("buttonSenderSingleInterfaceSettings")
        self.gridLayoutSinglePacket.addWidget(self.buttonSenderSingleInterfaceSettings, 1, 0, 1, 4)
        self.gridLayoutSinglePacketOverall.addLayout(self.gridLayoutSinglePacket, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutSinglePacketOverall.addItem(spacerItem3, 0, 1, 1, 1)
        self.tabWidgetSenderTabs.addTab(self.tabSinglePacket, "")
        self.tabAddSender = QtGui.QWidget()
        self.tabAddSender.setObjectName("tabAddSender")
        self.tabWidgetSenderTabs.addTab(self.tabAddSender, "")
        self.tabWidgetMain.addTab(self.tabSender, "")
        self.tabFuzzer = QtGui.QWidget()
        self.tabFuzzer.setObjectName("tabFuzzer")
        self.containerFuzzerData = QtGui.QWidget(self.tabFuzzer)
        self.containerFuzzerData.setGeometry(QtCore.QRect(10, 10, 791, 301))
        self.containerFuzzerData.setObjectName("containerFuzzerData")
        self.tableViewFuzzerData = QtGui.QTableView(self.containerFuzzerData)
        self.tableViewFuzzerData.setGeometry(QtCore.QRect(0, 0, 791, 301))
        self.tableViewFuzzerData.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableViewFuzzerData.setAlternatingRowColors(True)
        self.tableViewFuzzerData.setSortingEnabled(True)
        self.tableViewFuzzerData.setObjectName("tableViewFuzzerData")
        self.tableViewFuzzerData.horizontalHeader().setMinimumSectionSize(100)
        self.tableViewFuzzerData.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget3 = QtGui.QWidget(self.tabFuzzer)
        self.layoutWidget3.setGeometry(QtCore.QRect(820, 10, 346, 303))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayoutFuzzer = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayoutFuzzer.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutFuzzer.setObjectName("gridLayoutFuzzer")
        self.labelFuzzerTabMode = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerTabMode.setObjectName("labelFuzzerTabMode")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerTabMode, 0, 0, 1, 1)
        self.labelFuzzerTabIDMask = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerTabIDMask.setObjectName("labelFuzzerTabIDMask")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerTabIDMask, 2, 0, 1, 1)
        self.labelFuzzerTabDataMask = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerTabDataMask.setObjectName("labelFuzzerTabDataMask")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerTabDataMask, 3, 0, 1, 1)
        self.buttonFuzzerTabToggleFuzzing = QtGui.QPushButton(self.layoutWidget3)
        self.buttonFuzzerTabToggleFuzzing.setObjectName("buttonFuzzerTabToggleFuzzing")
        self.gridLayoutFuzzer.addWidget(self.buttonFuzzerTabToggleFuzzing, 17, 0, 1, 2)
        self.comboBoxFuzzingMode = QtGui.QComboBox(self.layoutWidget3)
        self.comboBoxFuzzingMode.setObjectName("comboBoxFuzzingMode")
        self.comboBoxFuzzingMode.addItem("")
        self.comboBoxFuzzingMode.addItem("")
        self.comboBoxFuzzingMode.addItem("")
        self.gridLayoutFuzzer.addWidget(self.comboBoxFuzzingMode, 0, 1, 1, 3)
        self.horizontalSliderFuzzerMinLength = QtGui.QSlider(self.layoutWidget3)
        self.horizontalSliderFuzzerMinLength.setMaximum(8)
        self.horizontalSliderFuzzerMinLength.setProperty("value", 0)
        self.horizontalSliderFuzzerMinLength.setSliderPosition(0)
        self.horizontalSliderFuzzerMinLength.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFuzzerMinLength.setInvertedAppearance(False)
        self.horizontalSliderFuzzerMinLength.setInvertedControls(False)
        self.horizontalSliderFuzzerMinLength.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSliderFuzzerMinLength.setObjectName("horizontalSliderFuzzerMinLength")
        self.gridLayoutFuzzer.addWidget(self.horizontalSliderFuzzerMinLength, 6, 0, 1, 2)
        self.lineEditFuzzerTabDataMask = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditFuzzerTabDataMask.setMaxLength(16)
        self.lineEditFuzzerTabDataMask.setObjectName("lineEditFuzzerTabDataMask")
        self.gridLayoutFuzzer.addWidget(self.lineEditFuzzerTabDataMask, 3, 1, 1, 3)
        self.lineEditFuzzerTabIDMask = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditFuzzerTabIDMask.setMaxLength(8)
        self.lineEditFuzzerTabIDMask.setObjectName("lineEditFuzzerTabIDMask")
        self.gridLayoutFuzzer.addWidget(self.lineEditFuzzerTabIDMask, 2, 1, 1, 3)
        self.horizontalSliderFuzzerMaxLength = QtGui.QSlider(self.layoutWidget3)
        self.horizontalSliderFuzzerMaxLength.setMaximum(8)
        self.horizontalSliderFuzzerMaxLength.setProperty("value", 8)
        self.horizontalSliderFuzzerMaxLength.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFuzzerMaxLength.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSliderFuzzerMaxLength.setObjectName("horizontalSliderFuzzerMaxLength")
        self.gridLayoutFuzzer.addWidget(self.horizontalSliderFuzzerMaxLength, 6, 2, 1, 2)
        self.buttonFuzzerClear = QtGui.QPushButton(self.layoutWidget3)
        self.buttonFuzzerClear.setObjectName("buttonFuzzerClear")
        self.gridLayoutFuzzer.addWidget(self.buttonFuzzerClear, 17, 2, 1, 2)
        self.labelFuzzerMinLengthDescr = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerMinLengthDescr.setObjectName("labelFuzzerMinLengthDescr")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerMinLengthDescr, 7, 0, 1, 1)
        self.labelFuzzerMinLengthValue = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerMinLengthValue.setObjectName("labelFuzzerMinLengthValue")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerMinLengthValue, 7, 1, 1, 1)
        self.labelFuzzerMaxLengthDescr = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerMaxLengthDescr.setObjectName("labelFuzzerMaxLengthDescr")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerMaxLengthDescr, 7, 2, 1, 1)
        self.labelFuzzerMaxLengthValue = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerMaxLengthValue.setObjectName("labelFuzzerMaxLengthValue")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerMaxLengthValue, 7, 3, 1, 1)
        self.labelFuzzerCountValue = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerCountValue.setObjectName("labelFuzzerCountValue")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerCountValue, 18, 2, 1, 2)
        self.labelFuzzerCountDescr = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerCountDescr.setObjectName("labelFuzzerCountDescr")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerCountDescr, 18, 0, 1, 2)
        self.labelFuzzerInterfaceValue = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerInterfaceValue.setEnabled(True)
        self.labelFuzzerInterfaceValue.setObjectName("labelFuzzerInterfaceValue")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerInterfaceValue, 14, 2, 1, 2)
        self.labelFuzzerInterfaceDescr = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerInterfaceDescr.setObjectName("labelFuzzerInterfaceDescr")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerInterfaceDescr, 14, 0, 1, 2)
        self.buttonFuzzerInterfaceSettings = QtGui.QPushButton(self.layoutWidget3)
        self.buttonFuzzerInterfaceSettings.setObjectName("buttonFuzzerInterfaceSettings")
        self.gridLayoutFuzzer.addWidget(self.buttonFuzzerInterfaceSettings, 13, 0, 1, 4)
        self.labelFuzzerTabPacketGap = QtGui.QLabel(self.layoutWidget3)
        self.labelFuzzerTabPacketGap.setObjectName("labelFuzzerTabPacketGap")
        self.gridLayoutFuzzer.addWidget(self.labelFuzzerTabPacketGap, 15, 0, 1, 2)
        self.doubleSpinBoxFuzzerPacketGap = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBoxFuzzerPacketGap.setMinimum(1.0)
        self.doubleSpinBoxFuzzerPacketGap.setMaximum(9000.0)
        self.doubleSpinBoxFuzzerPacketGap.setObjectName("doubleSpinBoxFuzzerPacketGap")
        self.gridLayoutFuzzer.addWidget(self.doubleSpinBoxFuzzerPacketGap, 15, 2, 1, 2)
        self.tabWidgetMain.addTab(self.tabFuzzer, "")
        self.tabComparer = QtGui.QWidget()
        self.tabComparer.setObjectName("tabComparer")
        self.tableViewComparerData = QtGui.QTableView(self.tabComparer)
        self.tableViewComparerData.setGeometry(QtCore.QRect(10, 10, 791, 301))
        self.tableViewComparerData.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableViewComparerData.setAlternatingRowColors(True)
        self.tableViewComparerData.setSortingEnabled(True)
        self.tableViewComparerData.setObjectName("tableViewComparerData")
        self.tableViewComparerData.horizontalHeader().setMinimumSectionSize(100)
        self.tableViewComparerData.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget4 = QtGui.QWidget(self.tabComparer)
        self.layoutWidget4.setGeometry(QtCore.QRect(830, 10, 331, 301))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayoutComparer = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayoutComparer.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutComparer.setObjectName("gridLayoutComparer")
        self.buttonComparerLoadSet1 = QtGui.QPushButton(self.layoutWidget4)
        self.buttonComparerLoadSet1.setObjectName("buttonComparerLoadSet1")
        self.gridLayoutComparer.addWidget(self.buttonComparerLoadSet1, 1, 0, 1, 1)
        self.buttonComparerStartCompare = QtGui.QPushButton(self.layoutWidget4)
        self.buttonComparerStartCompare.setObjectName("buttonComparerStartCompare")
        self.gridLayoutComparer.addWidget(self.buttonComparerStartCompare, 3, 0, 1, 1)
        self.buttonComparerLoadSet2 = QtGui.QPushButton(self.layoutWidget4)
        self.buttonComparerLoadSet2.setObjectName("buttonComparerLoadSet2")
        self.gridLayoutComparer.addWidget(self.buttonComparerLoadSet2, 2, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutComparer.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutComparer.addItem(spacerItem5, 4, 0, 1, 1)
        self.tabWidgetMain.addTab(self.tabComparer, "")
        self.tabSearcher = QtGui.QWidget()
        self.tabSearcher.setObjectName("tabSearcher")
        self.containerSearcherData = QtGui.QWidget(self.tabSearcher)
        self.containerSearcherData.setGeometry(QtCore.QRect(10, 10, 791, 301))
        self.containerSearcherData.setObjectName("containerSearcherData")
        self.tableViewSearcherData = QtGui.QTableView(self.containerSearcherData)
        self.tableViewSearcherData.setGeometry(QtCore.QRect(0, 0, 791, 301))
        self.tableViewSearcherData.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableViewSearcherData.setAlternatingRowColors(True)
        self.tableViewSearcherData.setSortingEnabled(True)
        self.tableViewSearcherData.setObjectName("tableViewSearcherData")
        self.tableViewSearcherData.horizontalHeader().setMinimumSectionSize(100)
        self.tableViewSearcherData.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget5 = QtGui.QWidget(self.tabSearcher)
        self.layoutWidget5.setGeometry(QtCore.QRect(880, 7, 226, 301))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayoutSearcher = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayoutSearcher.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutSearcher.setObjectName("gridLayoutSearcher")
        self.buttonSearcherStart = QtGui.QPushButton(self.layoutWidget5)
        self.buttonSearcherStart.setObjectName("buttonSearcherStart")
        self.gridLayoutSearcher.addWidget(self.buttonSearcherStart, 10, 0, 1, 2)
        self.lineSearcherSeperator2 = QtGui.QFrame(self.layoutWidget5)
        self.lineSearcherSeperator2.setFrameShape(QtGui.QFrame.HLine)
        self.lineSearcherSeperator2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineSearcherSeperator2.setObjectName("lineSearcherSeperator2")
        self.gridLayoutSearcher.addWidget(self.lineSearcherSeperator2, 11, 0, 1, 2)
        self.lineSearcherSeperator1 = QtGui.QFrame(self.layoutWidget5)
        self.lineSearcherSeperator1.setFrameShape(QtGui.QFrame.HLine)
        self.lineSearcherSeperator1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineSearcherSeperator1.setObjectName("lineSearcherSeperator1")
        self.gridLayoutSearcher.addWidget(self.lineSearcherSeperator1, 2, 0, 1, 2)
        self.buttonSearcherAddPacket = QtGui.QPushButton(self.layoutWidget5)
        self.buttonSearcherAddPacket.setObjectName("buttonSearcherAddPacket")
        self.gridLayoutSearcher.addWidget(self.buttonSearcherAddPacket, 1, 0, 1, 2)
        self.buttonSearcherInterfaceSettings = QtGui.QPushButton(self.layoutWidget5)
        self.buttonSearcherInterfaceSettings.setObjectName("buttonSearcherInterfaceSettings")
        self.gridLayoutSearcher.addWidget(self.buttonSearcherInterfaceSettings, 4, 0, 1, 2)
        self.buttonSearcherDataClear = QtGui.QPushButton(self.layoutWidget5)
        self.buttonSearcherDataClear.setObjectName("buttonSearcherDataClear")
        self.gridLayoutSearcher.addWidget(self.buttonSearcherDataClear, 12, 0, 1, 2)
        self.labelSearcherInterfaceValue = QtGui.QLabel(self.layoutWidget5)
        self.labelSearcherInterfaceValue.setEnabled(True)
        self.labelSearcherInterfaceValue.setObjectName("labelSearcherInterfaceValue")
        self.gridLayoutSearcher.addWidget(self.labelSearcherInterfaceValue, 6, 1, 1, 1)
        self.labelSearcherInterfaceDescr = QtGui.QLabel(self.layoutWidget5)
        self.labelSearcherInterfaceDescr.setObjectName("labelSearcherInterfaceDescr")
        self.gridLayoutSearcher.addWidget(self.labelSearcherInterfaceDescr, 6, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutSearcher.addItem(spacerItem6, 8, 0, 1, 1)
        self.labelSearcherPacketGap = QtGui.QLabel(self.layoutWidget5)
        self.labelSearcherPacketGap.setObjectName("labelSearcherPacketGap")
        self.gridLayoutSearcher.addWidget(self.labelSearcherPacketGap, 7, 0, 1, 1)
        self.doubleSpinBoxSearcherPacketGap = QtGui.QDoubleSpinBox(self.layoutWidget5)
        self.doubleSpinBoxSearcherPacketGap.setMinimum(1.0)
        self.doubleSpinBoxSearcherPacketGap.setMaximum(9000.0)
        self.doubleSpinBoxSearcherPacketGap.setObjectName("doubleSpinBoxSearcherPacketGap")
        self.gridLayoutSearcher.addWidget(self.doubleSpinBoxSearcherPacketGap, 7, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutSearcher.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutSearcher.addItem(spacerItem8, 13, 0, 1, 1)
        self.tabWidgetMain.addTab(self.tabSearcher, "")
        self.tabFilter = QtGui.QWidget()
        self.tabFilter.setObjectName("tabFilter")
        self.containerFilterData = QtGui.QWidget(self.tabFilter)
        self.containerFilterData.setGeometry(QtCore.QRect(10, 10, 791, 301))
        self.containerFilterData.setObjectName("containerFilterData")
        self.tableViewFilterData = QtGui.QTableView(self.containerFilterData)
        self.tableViewFilterData.setGeometry(QtCore.QRect(0, 0, 791, 301))
        self.tableViewFilterData.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableViewFilterData.setAlternatingRowColors(True)
        self.tableViewFilterData.setSortingEnabled(True)
        self.tableViewFilterData.setObjectName("tableViewFilterData")
        self.tableViewFilterData.horizontalHeader().setMinimumSectionSize(100)
        self.tableViewFilterData.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget6 = QtGui.QWidget(self.tabFilter)
        self.layoutWidget6.setGeometry(QtCore.QRect(850, 10, 305, 301))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayoutFilter = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayoutFilter.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutFilter.setObjectName("gridLayoutFilter")
        self.lineFilter1 = QtGui.QFrame(self.layoutWidget6)
        self.lineFilter1.setFrameShape(QtGui.QFrame.HLine)
        self.lineFilter1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFilter1.setObjectName("lineFilter1")
        self.gridLayoutFilter.addWidget(self.lineFilter1, 3, 0, 1, 3)
        self.spinBoxFilterTimeCollectNoise = QtGui.QSpinBox(self.layoutWidget6)
        self.spinBoxFilterTimeCollectNoise.setMaximum(999999)
        self.spinBoxFilterTimeCollectNoise.setObjectName("spinBoxFilterTimeCollectNoise")
        self.gridLayoutFilter.addWidget(self.spinBoxFilterTimeCollectNoise, 1, 2, 1, 1)
        self.buttonFilterStart = QtGui.QPushButton(self.layoutWidget6)
        self.buttonFilterStart.setObjectName("buttonFilterStart")
        self.gridLayoutFilter.addWidget(self.buttonFilterStart, 9, 0, 1, 3)
        self.buttonFilterDataClear = QtGui.QPushButton(self.layoutWidget6)
        self.buttonFilterDataClear.setObjectName("buttonFilterDataClear")
        self.gridLayoutFilter.addWidget(self.buttonFilterDataClear, 10, 0, 1, 3)
        self.labelFilterNoiseCollectSeconds = QtGui.QLabel(self.layoutWidget6)
        self.labelFilterNoiseCollectSeconds.setObjectName("labelFilterNoiseCollectSeconds")
        self.gridLayoutFilter.addWidget(self.labelFilterNoiseCollectSeconds, 1, 0, 1, 2)
        self.spinBoxFilterSampleAmount = QtGui.QSpinBox(self.layoutWidget6)
        self.spinBoxFilterSampleAmount.setMinimum(2)
        self.spinBoxFilterSampleAmount.setObjectName("spinBoxFilterSampleAmount")
        self.gridLayoutFilter.addWidget(self.spinBoxFilterSampleAmount, 2, 2, 1, 1)
        self.labelFilterSampleAmount = QtGui.QLabel(self.layoutWidget6)
        self.labelFilterSampleAmount.setObjectName("labelFilterSampleAmount")
        self.gridLayoutFilter.addWidget(self.labelFilterSampleAmount, 2, 0, 1, 2)
        self.buttonFilterInterfaceSettings = QtGui.QPushButton(self.layoutWidget6)
        self.buttonFilterInterfaceSettings.setObjectName("buttonFilterInterfaceSettings")
        self.gridLayoutFilter.addWidget(self.buttonFilterInterfaceSettings, 4, 0, 1, 3)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutFilter.addItem(spacerItem9, 11, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutFilter.addItem(spacerItem10, 0, 0, 1, 1)
        self.labelFilterInterfaceDescr = QtGui.QLabel(self.layoutWidget6)
        self.labelFilterInterfaceDescr.setObjectName("labelFilterInterfaceDescr")
        self.gridLayoutFilter.addWidget(self.labelFilterInterfaceDescr, 7, 0, 1, 1)
        self.labelFilterInterfaceValue = QtGui.QLabel(self.layoutWidget6)
        self.labelFilterInterfaceValue.setEnabled(True)
        self.labelFilterInterfaceValue.setObjectName("labelFilterInterfaceValue")
        self.gridLayoutFilter.addWidget(self.labelFilterInterfaceValue, 7, 1, 1, 2)
        self.tabWidgetMain.addTab(self.tabFilter, "")
        self.tabManager = QtGui.QWidget()
        self.tabManager.setObjectName("tabManager")
        self.tabWidgetManagerTabs = QtGui.QTabWidget(self.tabManager)
        self.tabWidgetManagerTabs.setGeometry(QtCore.QRect(0, 0, 1181, 331))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tabWidgetManagerTabs.setFont(font)
        self.tabWidgetManagerTabs.setObjectName("tabWidgetManagerTabs")
        self.tabProjects = QtGui.QWidget()
        self.tabProjects.setObjectName("tabProjects")
        self.groupBoxProjectManager = QtGui.QGroupBox(self.tabProjects)
        self.groupBoxProjectManager.setGeometry(QtCore.QRect(10, 10, 1151, 251))
        self.groupBoxProjectManager.setObjectName("groupBoxProjectManager")
        self.groupBoxProjectDelete = QtGui.QGroupBox(self.groupBoxProjectManager)
        self.groupBoxProjectDelete.setGeometry(QtCore.QRect(310, 40, 431, 121))
        self.groupBoxProjectDelete.setObjectName("groupBoxProjectDelete")
        self.layoutWidget7 = QtGui.QWidget(self.groupBoxProjectDelete)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 30, 411, 81))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayoutProjectDelete = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayoutProjectDelete.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutProjectDelete.setObjectName("gridLayoutProjectDelete")
        self.labelProjectDelete = QtGui.QLabel(self.layoutWidget7)
        self.labelProjectDelete.setObjectName("labelProjectDelete")
        self.gridLayoutProjectDelete.addWidget(self.labelProjectDelete, 0, 0, 1, 1)
        self.comboBoxProjectDelete = QtGui.QComboBox(self.layoutWidget7)
        self.comboBoxProjectDelete.setObjectName("comboBoxProjectDelete")
        self.gridLayoutProjectDelete.addWidget(self.comboBoxProjectDelete, 0, 1, 1, 1)
        self.buttonProjectDelete = QtGui.QPushButton(self.layoutWidget7)
        self.buttonProjectDelete.setObjectName("buttonProjectDelete")
        self.gridLayoutProjectDelete.addWidget(self.buttonProjectDelete, 1, 0, 1, 2)
        self.groupBoxProjectEdit = QtGui.QGroupBox(self.groupBoxProjectManager)
        self.groupBoxProjectEdit.setGeometry(QtCore.QRect(760, 40, 371, 181))
        self.groupBoxProjectEdit.setObjectName("groupBoxProjectEdit")
        self.layoutWidget8 = QtGui.QWidget(self.groupBoxProjectEdit)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 30, 351, 141))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayoutProjectEdit = QtGui.QGridLayout(self.layoutWidget8)
        self.gridLayoutProjectEdit.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutProjectEdit.setObjectName("gridLayoutProjectEdit")
        self.labelProjectEdit = QtGui.QLabel(self.layoutWidget8)
        self.labelProjectEdit.setObjectName("labelProjectEdit")
        self.gridLayoutProjectEdit.addWidget(self.labelProjectEdit, 0, 0, 1, 2)
        self.comboBoxProjectEdit = QtGui.QComboBox(self.layoutWidget8)
        self.comboBoxProjectEdit.setObjectName("comboBoxProjectEdit")
        self.gridLayoutProjectEdit.addWidget(self.comboBoxProjectEdit, 0, 2, 1, 1)
        self.labelProjectEditName = QtGui.QLabel(self.layoutWidget8)
        self.labelProjectEditName.setObjectName("labelProjectEditName")
        self.gridLayoutProjectEdit.addWidget(self.labelProjectEditName, 1, 0, 1, 1)
        self.labelProjectEditDescription = QtGui.QLabel(self.layoutWidget8)
        self.labelProjectEditDescription.setObjectName("labelProjectEditDescription")
        self.gridLayoutProjectEdit.addWidget(self.labelProjectEditDescription, 2, 0, 1, 1)
        self.buttonProjectEdit = QtGui.QPushButton(self.layoutWidget8)
        self.buttonProjectEdit.setObjectName("buttonProjectEdit")
        self.gridLayoutProjectEdit.addWidget(self.buttonProjectEdit, 3, 0, 1, 3)
        self.lineEditProjectEditName = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEditProjectEditName.setObjectName("lineEditProjectEditName")
        self.gridLayoutProjectEdit.addWidget(self.lineEditProjectEditName, 1, 2, 1, 1)
        self.lineEditProjectEditDescription = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEditProjectEditDescription.setObjectName("lineEditProjectEditDescription")
        self.gridLayoutProjectEdit.addWidget(self.lineEditProjectEditDescription, 2, 2, 1, 1)
        self.groupBoxCreateProject = QtGui.QGroupBox(self.tabProjects)
        self.groupBoxCreateProject.setGeometry(QtCore.QRect(40, 50, 261, 181))
        self.groupBoxCreateProject.setObjectName("groupBoxCreateProject")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBoxCreateProject)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 241, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayoutCreateProject = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayoutCreateProject.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCreateProject.setObjectName("gridLayoutCreateProject")
        self.lineEditProjectName = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditProjectName.setObjectName("lineEditProjectName")
        self.gridLayoutCreateProject.addWidget(self.lineEditProjectName, 0, 1, 1, 1)
        self.labelProjectDescription = QtGui.QLabel(self.layoutWidget_2)
        self.labelProjectDescription.setObjectName("labelProjectDescription")
        self.gridLayoutCreateProject.addWidget(self.labelProjectDescription, 1, 0, 1, 1)
        self.lineEditProjectDescription = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEditProjectDescription.setObjectName("lineEditProjectDescription")
        self.gridLayoutCreateProject.addWidget(self.lineEditProjectDescription, 1, 1, 1, 1)
        self.buttonProjectCreate = QtGui.QPushButton(self.layoutWidget_2)
        self.buttonProjectCreate.setObjectName("buttonProjectCreate")
        self.gridLayoutCreateProject.addWidget(self.buttonProjectCreate, 2, 0, 1, 2)
        self.labelProjectName = QtGui.QLabel(self.layoutWidget_2)
        self.labelProjectName.setObjectName("labelProjectName")
        self.gridLayoutCreateProject.addWidget(self.labelProjectName, 0, 0, 1, 1)
        self.tabWidgetManagerTabs.addTab(self.tabProjects, "")
        self.tabDumps = QtGui.QWidget()
        self.tabDumps.setObjectName("tabDumps")
        self.containerManagerDumpsData = QtGui.QWidget(self.tabDumps)
        self.containerManagerDumpsData.setGeometry(QtCore.QRect(10, 10, 831, 271))
        self.containerManagerDumpsData.setObjectName("containerManagerDumpsData")
        self.tableViewManagerDumpsData = QtGui.QTableView(self.containerManagerDumpsData)
        self.tableViewManagerDumpsData.setGeometry(QtCore.QRect(0, 0, 831, 271))
        self.tableViewManagerDumpsData.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableViewManagerDumpsData.setToolTip("")
        self.tableViewManagerDumpsData.setAlternatingRowColors(True)
        self.tableViewManagerDumpsData.setSortingEnabled(True)
        self.tableViewManagerDumpsData.setObjectName("tableViewManagerDumpsData")
        self.tableViewManagerDumpsData.horizontalHeader().setMinimumSectionSize(100)
        self.tableViewManagerDumpsData.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget9 = QtGui.QWidget(self.tabDumps)
        self.layoutWidget9.setGeometry(QtCore.QRect(860, 10, 271, 271))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.gridLayoutDumps = QtGui.QGridLayout(self.layoutWidget9)
        self.gridLayoutDumps.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutDumps.setObjectName("gridLayoutDumps")
        self.buttonManagerDeleteDump = QtGui.QPushButton(self.layoutWidget9)
        self.buttonManagerDeleteDump.setObjectName("buttonManagerDeleteDump")
        self.gridLayoutDumps.addWidget(self.buttonManagerDeleteDump, 0, 2, 1, 1)
        self.buttonManagerDumpsAddPacket = QtGui.QPushButton(self.layoutWidget9)
        self.buttonManagerDumpsAddPacket.setObjectName("buttonManagerDumpsAddPacket")
        self.gridLayoutDumps.addWidget(self.buttonManagerDumpsAddPacket, 1, 0, 1, 3)
        self.buttonManagerDumpsSaveToFile = QtGui.QPushButton(self.layoutWidget9)
        self.buttonManagerDumpsSaveToFile.setObjectName("buttonManagerDumpsSaveToFile")
        self.gridLayoutDumps.addWidget(self.buttonManagerDumpsSaveToFile, 4, 0, 1, 3)
        self.comboBoxManagerDumps = QtGui.QComboBox(self.layoutWidget9)
        self.comboBoxManagerDumps.setObjectName("comboBoxManagerDumps")
        self.gridLayoutDumps.addWidget(self.comboBoxManagerDumps, 0, 0, 1, 2)
        self.buttonManagerClearDump = QtGui.QPushButton(self.layoutWidget9)
        self.buttonManagerClearDump.setObjectName("buttonManagerClearDump")
        self.gridLayoutDumps.addWidget(self.buttonManagerClearDump, 5, 0, 1, 3)
        self.buttonManagerUpdateDump = QtGui.QPushButton(self.layoutWidget9)
        self.buttonManagerUpdateDump.setObjectName("buttonManagerUpdateDump")
        self.gridLayoutDumps.addWidget(self.buttonManagerUpdateDump, 2, 0, 1, 3)
        self.buttonManagerCreateDump = QtGui.QPushButton(self.layoutWidget9)
        self.buttonManagerCreateDump.setObjectName("buttonManagerCreateDump")
        self.gridLayoutDumps.addWidget(self.buttonManagerCreateDump, 3, 0, 1, 3)
        self.tabWidgetManagerTabs.addTab(self.tabDumps, "")
        self.tabKnownPackets = QtGui.QWidget()
        self.tabKnownPackets.setObjectName("tabKnownPackets")
        self.groupBoxManagerKnownPackets = QtGui.QGroupBox(self.tabKnownPackets)
        self.groupBoxManagerKnownPackets.setGeometry(QtCore.QRect(10, 10, 1151, 261))
        self.groupBoxManagerKnownPackets.setObjectName("groupBoxManagerKnownPackets")
        self.groupBoxManagerAddKnownPacket = QtGui.QGroupBox(self.groupBoxManagerKnownPackets)
        self.groupBoxManagerAddKnownPacket.setGeometry(QtCore.QRect(40, 30, 311, 211))
        self.groupBoxManagerAddKnownPacket.setObjectName("groupBoxManagerAddKnownPacket")
        self.layoutWidget10 = QtGui.QWidget(self.groupBoxManagerAddKnownPacket)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 30, 291, 171))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayoutAddKnownPacket = QtGui.QGridLayout(self.layoutWidget10)
        self.gridLayoutAddKnownPacket.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutAddKnownPacket.setObjectName("gridLayoutAddKnownPacket")
        self.labelAddKnownPacketID = QtGui.QLabel(self.layoutWidget10)
        self.labelAddKnownPacketID.setObjectName("labelAddKnownPacketID")
        self.gridLayoutAddKnownPacket.addWidget(self.labelAddKnownPacketID, 0, 0, 1, 1)
        self.lineEditKnownPacketID = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEditKnownPacketID.setObjectName("lineEditKnownPacketID")
        self.gridLayoutAddKnownPacket.addWidget(self.lineEditKnownPacketID, 0, 1, 1, 1)
        self.lineEditKnownPacketData = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEditKnownPacketData.setObjectName("lineEditKnownPacketData")
        self.gridLayoutAddKnownPacket.addWidget(self.lineEditKnownPacketData, 1, 1, 1, 1)
        self.labelAddKnownPacketDescription = QtGui.QLabel(self.layoutWidget10)
        self.labelAddKnownPacketDescription.setObjectName("labelAddKnownPacketDescription")
        self.gridLayoutAddKnownPacket.addWidget(self.labelAddKnownPacketDescription, 2, 0, 1, 1)
        self.labelAddKnownPacketData = QtGui.QLabel(self.layoutWidget10)
        self.labelAddKnownPacketData.setObjectName("labelAddKnownPacketData")
        self.gridLayoutAddKnownPacket.addWidget(self.labelAddKnownPacketData, 1, 0, 1, 1)
        self.buttonAddKnownPacket = QtGui.QPushButton(self.layoutWidget10)
        self.buttonAddKnownPacket.setObjectName("buttonAddKnownPacket")
        self.gridLayoutAddKnownPacket.addWidget(self.buttonAddKnownPacket, 3, 0, 1, 2)
        self.lineEditKnownPacketDescription = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEditKnownPacketDescription.setObjectName("lineEditKnownPacketDescription")
        self.gridLayoutAddKnownPacket.addWidget(self.lineEditKnownPacketDescription, 2, 1, 1, 1)
        self.groupBoxManagerDeleteKnownPacket = QtGui.QGroupBox(self.groupBoxManagerKnownPackets)
        self.groupBoxManagerDeleteKnownPacket.setGeometry(QtCore.QRect(370, 30, 401, 121))
        self.groupBoxManagerDeleteKnownPacket.setObjectName("groupBoxManagerDeleteKnownPacket")
        self.layoutWidget11 = QtGui.QWidget(self.groupBoxManagerDeleteKnownPacket)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 30, 381, 81))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridLayoutDeleteKnownPacket = QtGui.QGridLayout(self.layoutWidget11)
        self.gridLayoutDeleteKnownPacket.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutDeleteKnownPacket.setObjectName("gridLayoutDeleteKnownPacket")
        self.labelManagerDeleteKnownPacketItem = QtGui.QLabel(self.layoutWidget11)
        self.labelManagerDeleteKnownPacketItem.setObjectName("labelManagerDeleteKnownPacketItem")
        self.gridLayoutDeleteKnownPacket.addWidget(self.labelManagerDeleteKnownPacketItem, 0, 0, 1, 1)
        self.comboBoxDeleteKnownPackets = QtGui.QComboBox(self.layoutWidget11)
        self.comboBoxDeleteKnownPackets.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBoxDeleteKnownPackets.setObjectName("comboBoxDeleteKnownPackets")
        self.gridLayoutDeleteKnownPacket.addWidget(self.comboBoxDeleteKnownPackets, 0, 1, 1, 1)
        self.buttonKnownPacketRemove = QtGui.QPushButton(self.layoutWidget11)
        self.buttonKnownPacketRemove.setObjectName("buttonKnownPacketRemove")
        self.gridLayoutDeleteKnownPacket.addWidget(self.buttonKnownPacketRemove, 1, 0, 1, 2)
        self.groupBoxManagerEditKnownPacket = QtGui.QGroupBox(self.groupBoxManagerKnownPackets)
        self.groupBoxManagerEditKnownPacket.setGeometry(QtCore.QRect(790, 30, 341, 221))
        self.groupBoxManagerEditKnownPacket.setObjectName("groupBoxManagerEditKnownPacket")
        self.layoutWidget12 = QtGui.QWidget(self.groupBoxManagerEditKnownPacket)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 30, 321, 184))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.gridLayoutEditKnownPacket = QtGui.QGridLayout(self.layoutWidget12)
        self.gridLayoutEditKnownPacket.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutEditKnownPacket.setObjectName("gridLayoutEditKnownPacket")
        self.labelManagerEditKnownPacketDescription = QtGui.QLabel(self.layoutWidget12)
        self.labelManagerEditKnownPacketDescription.setObjectName("labelManagerEditKnownPacketDescription")
        self.gridLayoutEditKnownPacket.addWidget(self.labelManagerEditKnownPacketDescription, 3, 0, 1, 2)
        self.labelManagerEditKnownPacketData = QtGui.QLabel(self.layoutWidget12)
        self.labelManagerEditKnownPacketData.setObjectName("labelManagerEditKnownPacketData")
        self.gridLayoutEditKnownPacket.addWidget(self.labelManagerEditKnownPacketData, 2, 0, 1, 2)
        self.comboBoxEditKnownPackets = QtGui.QComboBox(self.layoutWidget12)
        self.comboBoxEditKnownPackets.setObjectName("comboBoxEditKnownPackets")
        self.gridLayoutEditKnownPacket.addWidget(self.comboBoxEditKnownPackets, 0, 2, 1, 1)
        self.lineEditKnownPacketEditDescription = QtGui.QLineEdit(self.layoutWidget12)
        self.lineEditKnownPacketEditDescription.setObjectName("lineEditKnownPacketEditDescription")
        self.gridLayoutEditKnownPacket.addWidget(self.lineEditKnownPacketEditDescription, 3, 2, 1, 1)
        self.lineEditKnownPacketEditData = QtGui.QLineEdit(self.layoutWidget12)
        self.lineEditKnownPacketEditData.setObjectName("lineEditKnownPacketEditData")
        self.gridLayoutEditKnownPacket.addWidget(self.lineEditKnownPacketEditData, 2, 2, 1, 1)
        self.buttonManagerEditKnownPacket = QtGui.QPushButton(self.layoutWidget12)
        self.buttonManagerEditKnownPacket.setObjectName("buttonManagerEditKnownPacket")
        self.gridLayoutEditKnownPacket.addWidget(self.buttonManagerEditKnownPacket, 4, 0, 1, 3)
        self.labelEditKnownPacketID = QtGui.QLabel(self.layoutWidget12)
        self.labelEditKnownPacketID.setObjectName("labelEditKnownPacketID")
        self.gridLayoutEditKnownPacket.addWidget(self.labelEditKnownPacketID, 1, 0, 1, 2)
        self.lineEditKnownPacketEditID = QtGui.QLineEdit(self.layoutWidget12)
        self.lineEditKnownPacketEditID.setObjectName("lineEditKnownPacketEditID")
        self.gridLayoutEditKnownPacket.addWidget(self.lineEditKnownPacketEditID, 1, 2, 1, 1)
        self.labelManagerEditKnownPacketItem = QtGui.QLabel(self.layoutWidget12)
        self.labelManagerEditKnownPacketItem.setObjectName("labelManagerEditKnownPacketItem")
        self.gridLayoutEditKnownPacket.addWidget(self.labelManagerEditKnownPacketItem, 0, 0, 1, 2)
        self.tabWidgetManagerTabs.addTab(self.tabKnownPackets, "")
        self.tabImportExport = QtGui.QWidget()
        self.tabImportExport.setObjectName("tabImportExport")
        self.layoutWidget13 = QtGui.QWidget(self.tabImportExport)
        self.layoutWidget13.setGeometry(QtCore.QRect(4, 10, 1161, 271))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.gridLayoutImportExport = QtGui.QGridLayout(self.layoutWidget13)
        self.gridLayoutImportExport.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutImportExport.setObjectName("gridLayoutImportExport")
        self.buttonManagerImport = QtGui.QPushButton(self.layoutWidget13)
        self.buttonManagerImport.setMinimumSize(QtCore.QSize(320, 0))
        self.buttonManagerImport.setObjectName("buttonManagerImport")
        self.gridLayoutImportExport.addWidget(self.buttonManagerImport, 2, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutImportExport.addItem(spacerItem11, 2, 0, 1, 1)
        self.buttonManagerExport = QtGui.QPushButton(self.layoutWidget13)
        self.buttonManagerExport.setMinimumSize(QtCore.QSize(320, 0))
        self.buttonManagerExport.setObjectName("buttonManagerExport")
        self.gridLayoutImportExport.addWidget(self.buttonManagerExport, 2, 3, 1, 2)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutImportExport.addItem(spacerItem12, 0, 3, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutImportExport.addItem(spacerItem13, 1, 5, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutImportExport.addItem(spacerItem14, 3, 3, 1, 1)
        self.labelImportExportProjectToExport = QtGui.QLabel(self.layoutWidget13)
        self.labelImportExportProjectToExport.setObjectName("labelImportExportProjectToExport")
        self.gridLayoutImportExport.addWidget(self.labelImportExportProjectToExport, 1, 3, 1, 1)
        self.comboBoxManagerExportProject = QtGui.QComboBox(self.layoutWidget13)
        self.comboBoxManagerExportProject.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxManagerExportProject.setObjectName("comboBoxManagerExportProject")
        self.gridLayoutImportExport.addWidget(self.comboBoxManagerExportProject, 1, 4, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayoutImportExport.addItem(spacerItem15, 2, 2, 1, 1)
        self.tabWidgetManagerTabs.addTab(self.tabImportExport, "")
        self.tabWidgetMain.addTab(self.tabManager, "")
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.gridLayoutWidget = QtGui.QWidget(self.tabAbout)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1171, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutAbout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutAbout.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutAbout.setObjectName("gridLayoutAbout")
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem16, 8, 7, 1, 1)
        self.labelLicense = QtGui.QLabel(self.gridLayoutWidget)
        self.labelLicense.setTextFormat(QtCore.Qt.RichText)
        self.labelLicense.setScaledContents(True)
        self.labelLicense.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLicense.setOpenExternalLinks(False)
        self.labelLicense.setObjectName("labelLicense")
        self.gridLayoutAbout.addWidget(self.labelLicense, 8, 2, 1, 5)
        self.labelAboutAt = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelAboutAt.setFont(font)
        self.labelAboutAt.setObjectName("labelAboutAt")
        self.gridLayoutAbout.addWidget(self.labelAboutAt, 5, 4, 1, 1)
        self.labelAboutCodedWith = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.labelAboutCodedWith.setFont(font)
        self.labelAboutCodedWith.setObjectName("labelAboutCodedWith")
        self.gridLayoutAbout.addWidget(self.labelAboutCodedWith, 5, 2, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutAbout.addItem(spacerItem17, 7, 2, 1, 1)
        self.labelAboutHeart = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.labelAboutHeart.setFont(font)
        self.labelAboutHeart.setStyleSheet("color: red")
        self.labelAboutHeart.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAboutHeart.setObjectName("labelAboutHeart")
        self.gridLayoutAbout.addWidget(self.labelAboutHeart, 5, 3, 1, 1)
        self.labelAboutDummy = QtGui.QLabel(self.gridLayoutWidget)
        self.labelAboutDummy.setText("")
        self.labelAboutDummy.setObjectName("labelAboutDummy")
        self.gridLayoutAbout.addWidget(self.labelAboutDummy, 4, 6, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutAbout.addItem(spacerItem18, 6, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem19, 1, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutAbout.addItem(spacerItem20, 4, 2, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem21, 1, 7, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem22, 5, 7, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem23, 5, 0, 1, 2)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem24, 8, 1, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem25, 2, 7, 1, 1)
        self.labelSWLogo = QtGui.QLabel(self.gridLayoutWidget)
        self.labelSWLogo.setMaximumSize(QtCore.QSize(300, 19))
        self.labelSWLogo.setText("")
        self.labelSWLogo.setPixmap(QtGui.QPixmap("icon/swlogo_small.png"))
        self.labelSWLogo.setScaledContents(True)
        self.labelSWLogo.setObjectName("labelSWLogo")
        self.gridLayoutAbout.addWidget(self.labelSWLogo, 5, 6, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayoutAbout.addItem(spacerItem26, 5, 5, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutAbout.addItem(spacerItem27, 1, 4, 1, 1)
        self.labelAboutForkMe = QtGui.QLabel(self.tabAbout)
        self.labelAboutForkMe.setGeometry(QtCore.QRect(0, 0, 215, 132))
        self.labelAboutForkMe.setText("")
        self.labelAboutForkMe.setPixmap(QtGui.QPixmap("icon/forkme.png"))
        self.labelAboutForkMe.setObjectName("labelAboutForkMe")
        self.labelAboutCANalyzat0r = QtGui.QLabel(self.tabAbout)
        self.labelAboutCANalyzat0r.setEnabled(True)
        self.labelAboutCANalyzat0r.setGeometry(QtCore.QRect(410, 30, 391, 71))
        font = QtGui.QFont()
        font.setFamily("OCRA")
        font.setPointSize(36)
        font.setWeight(75)
        font.setBold(True)
        self.labelAboutCANalyzat0r.setFont(font)
        self.labelAboutCANalyzat0r.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelAboutCANalyzat0r.setObjectName("labelAboutCANalyzat0r")
        self.tabWidgetMain.addTab(self.tabAbout, "")
        self.textBrowserLogs = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowserLogs.setGeometry(QtCore.QRect(10, 370, 1161, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserLogs.sizePolicy().hasHeightForWidth())
        self.textBrowserLogs.setSizePolicy(sizePolicy)
        self.textBrowserLogs.setMinimumSize(QtCore.QSize(1161, 311))
        self.textBrowserLogs.setMaximumSize(QtCore.QSize(1161, 311))
        self.textBrowserLogs.setTabStopWidth(80)
        self.textBrowserLogs.setObjectName("textBrowserLogs")
        self.lineSeperatorTextbrowserLogs = QtGui.QFrame(self.centralwidget)
        self.lineSeperatorTextbrowserLogs.setGeometry(QtCore.QRect(7, 350, 1161, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSeperatorTextbrowserLogs.sizePolicy().hasHeightForWidth())
        self.lineSeperatorTextbrowserLogs.setSizePolicy(sizePolicy)
        self.lineSeperatorTextbrowserLogs.setMinimumSize(QtCore.QSize(1161, 21))
        self.lineSeperatorTextbrowserLogs.setMaximumSize(QtCore.QSize(1161, 21))
        self.lineSeperatorTextbrowserLogs.setFrameShape(QtGui.QFrame.HLine)
        self.lineSeperatorTextbrowserLogs.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineSeperatorTextbrowserLogs.setObjectName("lineSeperatorTextbrowserLogs")
        CANalyzatorMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(CANalyzatorMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(1178, 22))
        self.statusbar.setMaximumSize(QtCore.QSize(1178, 22))
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        CANalyzatorMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CANalyzatorMainWindow)
        self.tabWidgetMain.setCurrentIndex(0)
        self.comboBoxLoglevel.setCurrentIndex(0)
        self.tabWidgetSnifferTabs.setCurrentIndex(0)
        self.tabWidgetSenderTabs.setCurrentIndex(1)
        self.tabWidgetManagerTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CANalyzatorMainWindow)

    def retranslateUi(self, CANalyzatorMainWindow):
        CANalyzatorMainWindow.setWindowTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "CANalyzat0r", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxIfaceConfig.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Global interface configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVCANRemove.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Remove vcan0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMainUseVCAN.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Virtual CAN interface", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonReadInterfaces.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Check interfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRate.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Bitrate (Bit/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonApplyInterface.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMainGlobalIface.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Global interface name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVCANIndex.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "VCAN index", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVCANAdd.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Add vcan0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMainCurrentProject.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Current project", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSetProject.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Set active", None, QtGui.QApplication.UnicodeUTF8))
        self.labelActiveProject.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Active project", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMainLogging.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLoglevel.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Min. Loglevel", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLoglevel.setItemText(0, QtGui.QApplication.translate("CANalyzatorMainWindow", "INFO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLoglevel.setItemText(1, QtGui.QApplication.translate("CANalyzatorMainWindow", "DEBUG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLoglevel.setItemText(2, QtGui.QApplication.translate("CANalyzatorMainWindow", "WARNING", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLoglevel.setItemText(3, QtGui.QApplication.translate("CANalyzatorMainWindow", "ERROR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxLoglevel.setItemText(4, QtGui.QApplication.translate("CANalyzatorMainWindow", "CRITICAL", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMainCANalyzat0r.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "CANalyzat0r", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabMain), QtGui.QApplication.translate("CANalyzatorMainWindow", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSnifferTabs.setTabText(self.tabWidgetSnifferTabs.indexOf(self.tabSnifferPlaceholder), QtGui.QApplication.translate("CANalyzatorMainWindow", "No interface", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabSniffer), QtGui.QApplication.translate("CANalyzatorMainWindow", "Sniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSenderSingleInterfaceDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSinglePacketID.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSinglePackeData.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSingleSend.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSenderSingleInterfaceValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSenderSingleInterfaceSettings.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSenderTabs.setTabText(self.tabWidgetSenderTabs.indexOf(self.tabSinglePacket), QtGui.QApplication.translate("CANalyzatorMainWindow", "Single packet", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSenderTabs.setTabText(self.tabWidgetSenderTabs.indexOf(self.tabAddSender), QtGui.QApplication.translate("CANalyzatorMainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabSender), QtGui.QApplication.translate("CANalyzatorMainWindow", "Sender", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerTabMode.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerTabIDMask.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "ID Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerTabDataMask.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Data Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFuzzerTabToggleFuzzing.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFuzzingMode.setItemText(0, QtGui.QApplication.translate("CANalyzatorMainWindow", "User specificed mask", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFuzzingMode.setItemText(1, QtGui.QApplication.translate("CANalyzatorMainWindow", "11 bit IDs", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFuzzingMode.setItemText(2, QtGui.QApplication.translate("CANalyzatorMainWindow", "29 bit IDs", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditFuzzerTabIDMask.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "XXX", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFuzzerClear.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerMinLengthDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Min. data length:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerMinLengthValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerMaxLengthDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Max. data length:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerMaxLengthValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerCountValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerCountDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Generated packets: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerInterfaceValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerInterfaceDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFuzzerInterfaceSettings.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFuzzerTabPacketGap.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Gap (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabFuzzer), QtGui.QApplication.translate("CANalyzatorMainWindow", "Fuzzer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonComparerLoadSet1.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Load packet set 1", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonComparerStartCompare.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Compare", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonComparerLoadSet2.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Load packet set 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabComparer), QtGui.QApplication.translate("CANalyzatorMainWindow", "Comparer", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSearcherStart.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSearcherAddPacket.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Add packet", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSearcherInterfaceSettings.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface settings", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSearcherDataClear.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSearcherInterfaceValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSearcherInterfaceDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSearcherPacketGap.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Gap (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabSearcher), QtGui.QApplication.translate("CANalyzatorMainWindow", "Searcher", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFilterStart.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFilterDataClear.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilterNoiseCollectSeconds.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Noise collect time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilterSampleAmount.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Sample amount", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFilterInterfaceSettings.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface settings", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilterInterfaceDescr.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Interface:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilterInterfaceValue.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabFilter), QtGui.QApplication.translate("CANalyzatorMainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxProjectManager.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Project management", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxProjectDelete.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectDelete.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Project to delete", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonProjectDelete.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxProjectEdit.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectEdit.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Project to edit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectEditName.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectEditDescription.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonProjectEdit.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxCreateProject.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectDescription.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonProjectCreate.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectName.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetManagerTabs.setTabText(self.tabWidgetManagerTabs.indexOf(self.tabProjects), QtGui.QApplication.translate("CANalyzatorMainWindow", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerDeleteDump.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Delete dump", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerDumpsAddPacket.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Add packet", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerDumpsSaveToFile.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Save to file", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerClearDump.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerUpdateDump.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Update dump", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerCreateDump.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Create dump", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetManagerTabs.setTabText(self.tabWidgetManagerTabs.indexOf(self.tabDumps), QtGui.QApplication.translate("CANalyzatorMainWindow", "Dumps", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxManagerKnownPackets.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Manage known packets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxManagerAddKnownPacket.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAddKnownPacketID.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAddKnownPacketDescription.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAddKnownPacketData.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Data (* = wildcard)", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddKnownPacket.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxManagerDeleteKnownPacket.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.labelManagerDeleteKnownPacketItem.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Item to remove", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonKnownPacketRemove.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxManagerEditKnownPacket.setTitle(QtGui.QApplication.translate("CANalyzatorMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelManagerEditKnownPacketDescription.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.labelManagerEditKnownPacketData.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Data (* = wildcard)", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerEditKnownPacket.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEditKnownPacketID.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.labelManagerEditKnownPacketItem.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Item to edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetManagerTabs.setTabText(self.tabWidgetManagerTabs.indexOf(self.tabKnownPackets), QtGui.QApplication.translate("CANalyzatorMainWindow", "Known packets", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerImport.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Import project", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonManagerExport.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Export project", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImportExportProjectToExport.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Project to export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetManagerTabs.setTabText(self.tabWidgetManagerTabs.indexOf(self.tabImportExport), QtGui.QApplication.translate("CANalyzatorMainWindow", "Import/Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabManager), QtGui.QApplication.translate("CANalyzatorMainWindow", "Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLicense.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Licensed under the GPLv3", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAboutAt.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "at", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAboutCodedWith.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "Coded with", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAboutHeart.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "♥", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAboutCANalyzat0r.setText(QtGui.QApplication.translate("CANalyzatorMainWindow", "CANalyzat0r", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabAbout), QtGui.QApplication.translate("CANalyzatorMainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
